# This is a

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull  events but only for the master branch
  push:
    branches: [ POC_Kumar_Revert ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  merge-branch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@master 
        
      - name: checkoutmerge
        uses: cesensw/AlanApps@master
        with:
          type: now
          from_branch: POC_Kumar_Revert
          target_branch: POC_Kumar
          github_token: ${{ github.AUTO_TOKEN }}
